#!/usr/bin/env bash

REVISION=$(cd $1 && git rev-parse HEAD)
VERSION=$(cd $1 && git describe)

git reset --hard
git checkout main
CURRENT_REVISION=$(sed -n "s/^.*revision: *\"\([^\"]*\)\".*$/\1/p" $2)

if [ "$REVISION" != "$CURRENT_REVISION" ]; then
  sed -i "s/\(revision: *\)\"[^\"]*\"/\1\"$REVISION\"/g" $2
  sed -i "s/\(version *\)\"[^\"]*\"/\1\"$VERSION\"/g" $2
fi
