name: Bump formulae on schedule or request

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

jobs:
  autobump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: clasp-developers/clasp
          path: clasp
          fetch-depth: 0
      - name: Update clasp-cl
        run: |
          ./bump-version clasp Formula/clasp-cl.rb
      - name: Create Pull Request for clasp-cl
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Bump clasp-cl version
          title: Bump clasp-cl version
          branch: bump-clasp-cl
          base: main
          labels: bump
      - name: Update cando
        run: |
          ./bump-version clasp Formula/cando.rb
      - name: Create Pull Request for cando
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Bump cando version
          title: Bump cando version
          branch: bump-cando
          base: main
          labels: bump

