name: Bump formulae on schedule or request

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

jobs:
  bump_clasp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: clasp-developers/clasp
          path: clasp
          fetch-depth: 0
      - name: Update path
        run: |
          echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH
      - name: Update clasp-cl
        run: |
          brew install sbcl
          ./bump-version clasp Formula/clasp-cl.rb
      - name: Create Pull Request for clasp-cl
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.REPO_TOKEN }}
          commit-message: Build clasp-cl
          title: Build clasp-cl
          branch: build-clasp-cl
          base: main
  bump_cando:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: clasp-developers/clasp
          path: clasp
          fetch-depth: 0
      - name: Update path
        run: |
          echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH
      - name: Update cando
        run: |
          brew install sbcl
          ./bump-version clasp Formula/cando.rb --extensions=cando,seqan-clasp
      - name: Create Pull Request for cando
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.REPO_TOKEN }}
          commit-message: Build cando
          title: Build cando
          branch: build-cando
          base: main

